using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ShopPhrasesLevel : MonoBehaviour
{
    [Header("׃נמגום פנאח")]
    [SerializeField] public int phrasesLevel;

    [Header("IDLE פנאח")]
    [SerializeField] public List<Sound> idlePhrases;

    [Header("ShopIn פנאח")]
    [SerializeField] public List<Sound> shopInPhrases;

    [Header("ShopOut פנאח")]
    [SerializeField] public List<Sound> shopOutPhrases;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
